#let links = (
  linkedin-label: "Michael Dyer",
  linkedin-url: "https://www.linkedin.com/in/michaelowendyer/",
  github-label: "MichaelOwenDyer",
  github-url: "https://github.com/MichaelOwenDyer",
  artemis-url: "https://github.com/ls1intum/Artemis",
  sz-url: "https://www.sueddeutsche.de/muenchen/ki-chatbot-chat-gpt-muenchen-tum-studium-lux.9NsArTJGvyeeHESKeNJias",
  paige-url: "https://chat.it.tum.de",
  goethe-url: "https://www.goethe.de/de/spr/stv/sbr.html",
  westchester-url: "https://wais.springbranchisd.com",
  petrivet-url: "https://github.com/MichaelOwenDyer/petrivet",
  rust-random-url: "https://github.com/rust-random",
  rand-url: "https://github.com/rust-random/rand",
  charts-url: "https://github.com/rust-random/charts",
  blackjack-url: "https://github.com/MichaelOwenDyer/Blackjack",
  mcc-2026-url: "https://mcc.lip6.fr/2026/results.php",
  dotfiles-url: "https://github.com/MichaelOwenDyer/dotfiles",
  lincoln-center-mozart-url: "https://www.youtube.com/watch?v=xX9hMYAa2Bw",
)